'use strict';
/* eslint-disable */
const config = {
	name: 'lg_tv',
	class: 'tv',
	icon: '../../ir_generator/assets/remote.svg',
	images: {
		small: '../../ir_generator/assets/images/small.jpg',
		large: '../../ir_generator/assets/images/large.jpg'
	},
	capabilities: ['onoff',
		'volume_mute',
		'volume_up',
		'volume_down',
		'channel_up',
		'channel_down'
	],
	capabilityToCommandMap: {
		onoff: ['POWER_ON', 'POWER_OFF', 'POWER_TOGGLE'],
		volume_mute: 'MUTE_TOGGLE',
		volume_up: 'VOLUME_UP',
		volume_down: 'VOLUME_DOWN',
		channel_up: 'CHANNEL_UP',
		channel_down: 'CHANNEL_DOWN'
	},
	signal: 'lg_tv',
	actions: [{
		id: 'lg_tv:send_cmd',
		title: 'ir_generator.flow.send_cmd',
		args: [{
			name: 'cmd',
			type: 'autocomplete'
		}, {
			name: 'device',
			type: 'device',
			filter: 'driver_id=lg_tv'
		}]
	}, {
		id: 'lg_tv:send_cmd_number',
		title: 'ir_generator.flow.send_cmd_number',
		args: [{
			name: 'number',
			type: 'number',
			min: '0',
			max: '9999'
		}, {
			name: 'device',
			type: 'device',
			filter: 'driver_id=lg_tv'
		}]
	}],
	pair: {
		viewOrder: ['generic_done'],
		views: [{
			template: '../lib/433/pair/done.html',
			options: {
				title: 'views.generic_done.title',
				prepend: '',
				append: ''
			},
			prepend: [],
			append: [],
			id: 'generic_done'
		}]
	},
	id: 'lg_tv',
	driver: '../lib/ir/driver',
	signalDefinition: {
		id: 'lg_tv',
		type: 'prontohex',
		repetitions: 1,
		options: {
			cmdNumberPrefix: 'DIGIT_',
			minTxInterval: 250
		},
		cmds: ['POWER_TOGGLE',
			'POWER_ON',
			'POWER_OFF',
			'VOLUME_UP',
			'VOLUME_DOWN',
			'MUTE_TOGGLE',
			'CHANNEL_UP',
			'CHANNEL_DOWN',
			'DIGIT_0',
			'DIGIT_1',
			'DIGIT_2',
			'DIGIT_3',
			'DIGIT_4',
			'DIGIT_5',
			'DIGIT_6',
			'DIGIT_7',
			'DIGIT_8',
			'DIGIT_9',
			'PREVIOUS_CHANNEL',
			'CHANNEL_SEARCH',
			'GUIDE',
			'TV_GUIDE',
			'TELETEXT',
			'CURSOR_UP',
			'CURSOR_LEFT',
			'CURSOR_RIGHT',
			'CURSOR_DOWN',
			'CURSOR_ENTER',
			'BACK',
			'ENTER',
			'EXIT',
			'PLAY',
			'PAUSE',
			'FORWARD',
			'REVERSE',
			'STOP',
			'RECORD',
			'RECORD_LIST',
			'MY_APPS',
			'FUNCTION_RED',
			'FUNCTION_GREEN',
			'FUNCTION_YELLOW',
			'FUNCTION_BLUE',
			'CC',
			'MENU_HOME',
			'MENU_LIVE',
			'MENU_MAIN',
			'MENU_PREMIUM',
			'MENU_QUICK',
			'MENU_SMART_HOME',
			'MENU_USB',
			'INFO',
			'BRIGHTNESS_DOWN',
			'BRIGHTNESS_UP',
			'INPUT_TV',
			'INPUT_HDMI_1',
			'INPUT_HDMI_2',
			'INPUT_HDMI_3',
			'INPUT_HDMI_4',
			'INPUT_ANTENNA',
			'INPUT_PC',
			'INPUT_DVI',
			'INPUT_DVI_PC_OR_HDMI_1',
			'INPUT_COMPONENT_1',
			'INPUT_COMPONENT_2',
			'INPUT_COMPONENT_3',
			'INPUT_VIDEO_1',
			'INPUT_VIDEO_2',
			'INPUT_VIDEO_3',
			'INPUT_VIDEO_4',
			'INPUT_VIDEO_5',
			'INPUT_USB',
			'INPUT_USB_PHOTO',
			'INPUT_USB_PHOTO_AND_MUSIC',
			'INPUT_RGB',
			'INPUT_RGB_1',
			'INPUT_RGB_2',
			'INPUT_RGB_DTV',
			'INPUT_RGB_PC',
			'INPUT_S_VIDEO',
			'INPUT_S_VIDEO_1',
			'INPUT_S_VIDEO_2',
			'INPUT_SCROLL',
			'INPUT_1394',
			'3D',
			'3D_ALTERNATE',
			'POWER_ON_AND_INPUT_VIDEO',
			'POWER_ON_AND_INPUT_VIDEO_1_OR_AV1',
			'POWER_ON_AND_INPUT_VIDEO_2_OR_AV2',
			'POWER_ON_AND_INPUT_VIDEO_3_OR_FRONT',
			'POWER_ON_AND_INPUT_VIDEO_4_OR_FRONT',
			'POWER_ON_AND_INPUT_VIDEO_5',
			'POWER_ON_AND_INPUT_PC',
			'POWER_ON_AND_INPUT_COMPONENT_OR_COMPONENT_1',
			'POWER_ON_AND_INPUT_RGB',
			'POWER_ON_AND_INPUT_S_VIDEO',
			'POWER_ON_AND_INPUT_S_VIDEO_1',
			'POWER_ON_AND_INPUT_S_VIDEO_2',
			'ADJUST',
			'APM',
			'AUTO_CONFIGURE',
			'AV_MODE',
			'CLEAR',
			'DASP',
			'DIGIT_SEPARATOR',
			'ENERGY_SAVING',
			'EZ_PICTURE',
			'EZ_SOUND',
			'FAVORITE',
			'FORMAT_169',
			'FORMAT_43',
			'FORMAT_AUTO',
			'FORMAT_SCROLL',
			'FORMAT_ZOOM',
			'FREEZE',
			'GO_TO_NEXT',
			'GO_TO_PREVIOUS',
			'LIST',
			'MC_EJECT',
			'NETCAST',
			'OPEN/CLOSE',
			'PICTURE',
			'PIP',
			'PIP_ARC',
			'PIP_CHANNEL_DOWN',
			'PIP_CHANNEL_UP',
			'PIP_FREEZE',
			'PIP_INPUT',
			'PIP_SWAP',
			'PORTAL',
			'PREMIUM',
			'RECENT',
			'SAP',
			'SIMPLINK',
			'SLEEP',
			'SOUND',
			'SPLIT_ZOOM',
			'SURF',
			'SYSTEM_OFF',
			'TEXT_OPTION',
			'TILE',
			'TIMER',
			'TOUCH',
			'TV/PC',
			'USB_EJECT',
			'USER_GUIDE',
			'VD/*',
			'WIDGETS',
			'X_STUDIO',
			'X_STUDIO_PRO',
			'ZOOM_IN',
			'ZOOM_OUT'
		]
	}
};
const Driver = require(config.driver);
const driver = new Driver(config);
module.exports = Object.assign(
  {},
	driver.getExports(), 
	{ init: (devices, callback) => driver.init(module.exports, devices, callback) }
);
